version: "2"
services:
  simple:
    build:
      context: ./simple
      dockerfile: ./Dockerfile
  vue:
    build:
      context: ./vue
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
