version: "2"
services:
  simple:
    build:
      context: ./simple
      dockerfile: ./Dockerfile
    volumes:
      # for dev
      - ./simple:/app
  vue:
    build:
      context: ./vue
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/app
