version: "2"
services:
  simple:
    build:
      context: ./simple
      dockerfile: ./Dockerfile
  vue:
    build:
      context: ./vue
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  rails:
    build:
      context: ./rails
      dockerfile: ./Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      RAILS_RELATIVE_URL_ROOT: /api
    ports:
      - "3000:3000"

  rails_prod:
    build:
      context: ./rails
      dockerfile: ./Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      RAILS_RELATIVE_URL_ROOT: /api
      RAILS_ENV: production
      SECRET_KEY_BASE: hogehogehogehogehoge
    command: rails s -b 0.0.0.0 -p 3001 -P tmp/pids/prod.pid
    ports:
      - "3001:3001"

  mysql:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  web:
    image: nginx:1.13.6
    ports:
      - "8001:8001"
    volumes:
      - ./vue:/app/vue
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/rails.conf:/etc/nginx/sites-enabled/rails.conf
      - ./nginx/conf/vue.conf:/etc/nginx/sites-enabled/vue.conf

volumes:
  db:

